In [1]:
import numpy as np

In [7]:
# Criar uma matriz ou array sao iguais (abaixo, 1 array unidimensional)
M = np.array([10, 24, 54, 78, 31])
N = np.array([34, 21, 45, 56, 98])
M
N

array([34, 21, 45, 56, 98])

In [4]:
type(M)

numpy.ndarray

In [5]:
print(M)

[10 24 54 78 31]


In [6]:
print('{}'.format(M))

[10 24 54 78 31]


In [8]:
print('{}'.format(M[2]))

54


In [9]:
print('{}'.format(M[10])) #nao tem 11 elementos no array

IndexError: index 10 is out of bounds for axis 0 with size 5

In [10]:
print('{}'.format(M[0:4]))

[10 24 54 78]


In [11]:
print(M.shape)

(5,)


In [12]:
MD = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
MD

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [13]:
print("{}".format(MD))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
MD.shape #mudou pq acrescentou 1 dimensao

(2, 6)

In [16]:
# trasnpondo uma matriz
transp = MD.T
print(transp)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [17]:
transp.shape

(6, 2)

In [18]:
MD

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
#batalha naval
MD[1,1]

8

In [21]:
#mesmo do anterior
MD[1][1]

8

In [22]:
MD[1],[1]

(array([ 7,  8,  9, 10, 11, 12]), [1])

In [24]:
MD.shape[0]  #qdo coloco 0 é para ver qtdade de linhas, 1 é para coluna

2

In [25]:
MD.shape[1]

6

In [ ]:
# Criar uma submatriz (linha 0 e 1) & (colunas 0, 1 e 2)

In [26]:
subMD = MD[0:2, 0:3]
print(subMD)

[[1 2 3]
 [7 8 9]]


In [ ]:
#modificar os elementos de uma matriz

In [27]:
MD[1,1] = 11
print("{}".format(MD))

[[ 1  2  3  4  5  6]
 [ 7 11  9 10 11 12]]


In [30]:
#TRANSFORMAR PARA NUMERO REAL (numeros com decimal)
MR = np.array([[1.0, 2, 3, 4, 5],[1000, 12, 32111, 788, 1],[6,7,8,9,1999]])
print(MR)
#basta ter 1 numero com virgula, faz com que os demais ja venham automaticamente

[[1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00 5.0000e+00]
 [1.0000e+03 1.2000e+01 3.2111e+04 7.8800e+02 1.0000e+00]
 [6.0000e+00 7.0000e+00 8.0000e+00 9.0000e+00 1.9990e+03]]


In [31]:
#matriz identidade (que tem diagonal
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
